version: '3.8'

services:
  ecommerce:
    build: ./ecommerce
    container_name: ecommerce
    ports:
      - "5050:5050"
    depends_on:
      - exchange1
      - exchange2
      - store
      - fidelity
  
  store:
    build: ./store
    container_name: store
    ports:
      - "5001:5001"

  exchange1:
    build: ./exchange
    container_name: exchange1
    ports:
      - "5011:5002"
  
  exchange2:
    build: ./exchange
    container_name: exchange2
    ports:
      - "5012:5002"

  fidelity:
    build: ./fidelity
    container_name: fidelity
    ports:
      - "5003:5003"

  